[package]
name = "db2rustapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ibm_db = "1.0"
rpassword = "7.2"
